# syntax=docker/dockerfile:1

FROM golang:1.26.2-alpine3.23 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o creator cmd/creator/main.go

FROM alpine:3.23

RUN apk add --no-cache ffmpeg ca-certificates && update-ca-certificates

WORKDIR /app
COPY --from=builder /app/creator .

CMD ["./creator"]
