# syntax=docker/dockerfile:1

FROM golang:1.26.2-alpine3.23 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o clipper cmd/clipper/main.go

FROM alpine:3.23

WORKDIR /app
COPY --from=builder /app/clipper .

EXPOSE 8081

CMD ["./clipper"]
